package arcanemaster.map;

public enum Resource { NONE, IRON, SILVER, GOLD, GEMS, ADAMANTIUM, NEVERIL, ELVEN_VILLAGE, INFERNAL_RIFT, MAGIC_FIELD, HOLY_GROUND,
	KOATL_VILLAGE, HALBERDHALL, MINOTAUR_CAVES, DONKEYS, ANCIENT_RUINS, MAGIC_NODE

}
